# ---------------------------------------------
# ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
# Source: backend/db/data_models/__init__.py
# Generated by: backend/db/scripts/generate_crud_schemas.py
# ---------------------------------------------

from datetime import datetime
from typing import Any, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict
from sqlmodel import Field

from db.data_models import (
    ActorType,
    AssetUploadStatus,
    BackgroundType,
    CommentStatus,
    FontStyle,
    GiftcardProvider,
    GiftcardStatus,
    JobEventAction,
    JobStatus,
    NotificationDeliveryEvent,
    NotificationStatus,
    NotificationType,
    OpenConfetti,
    OpenStyle,
    PageLayout,
    PaymentEventSource,
    PaymentPurpose,
    PaymentStatus,
    PhotobookStatus,
    PhotobookStatusEditor,
    ShareAccessPolicy,
    ShareChannelStatus,
    ShareChannelType,
    ShareKind,
    ShareNotificationType,
    ShareProvider,
    ShareRole,
    SubscriptionStatus,
    UserProvidedOccasion,
)


class WritableModel(BaseModel):
    model_config = ConfigDict(populate_by_name=True)  # used for Create/Update


class DAOAssetsCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    asset_key_original: Optional[str] = None
    asset_key_display: Optional[str] = None
    asset_key_llm: Optional[str] = None
    metadata_json: Optional[dict[str, Any]] = None
    original_photobook_id: Optional[UUID] = None
    upload_status: AssetUploadStatus
    original_filename: Optional[str] = None
    exif: Optional[dict[str, Any]] = None
    blur_data_url: Optional[str] = None
    asset_key_thumbnail: Optional[str] = None
    user_id: UUID


class DAOAssetsUpdate(WritableModel):
    asset_key_original: Optional[str] = None
    asset_key_display: Optional[str] = None
    asset_key_llm: Optional[str] = None
    metadata_json: Optional[dict[str, Any]] = None
    original_photobook_id: Optional[UUID] = None
    upload_status: Optional[AssetUploadStatus] = None
    original_filename: Optional[str] = None
    exif: Optional[dict[str, Any]] = None
    blur_data_url: Optional[str] = None
    asset_key_thumbnail: Optional[str] = None
    user_id: Optional[UUID] = None


class DAOEntitlementsCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    user_id: UUID
    key: str
    active: bool
    expires_at: Optional[datetime] = None


class DAOEntitlementsUpdate(WritableModel):
    user_id: Optional[UUID] = None
    key: Optional[str] = None
    active: Optional[bool] = None
    expires_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class DAOGiftcardsCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    share_id: UUID
    created_by_payment_id: Optional[UUID] = None
    created_by_user_id: Optional[UUID] = None
    amount_total: int
    currency: str
    provider: Optional[GiftcardProvider] = None
    brand_code: Optional[str] = None
    giftcard_code_explicit_override: Optional[str] = None
    status: GiftcardStatus
    granted_at: datetime
    issued_at: Optional[datetime] = None
    redeemed_at: Optional[datetime] = None
    canceled_at: Optional[datetime] = None
    expires_at: Optional[datetime] = None
    description: Optional[str] = None
    metadata_json: dict[str, Any]
    provider_giftcard_id_internal_only: UUID


class DAOGiftcardsUpdate(WritableModel):
    share_id: Optional[UUID] = None
    created_by_payment_id: Optional[UUID] = None
    created_by_user_id: Optional[UUID] = None
    amount_total: Optional[int] = None
    currency: Optional[str] = None
    provider: Optional[GiftcardProvider] = None
    brand_code: Optional[str] = None
    giftcard_code_explicit_override: Optional[str] = None
    status: Optional[GiftcardStatus] = None
    granted_at: Optional[datetime] = None
    issued_at: Optional[datetime] = None
    redeemed_at: Optional[datetime] = None
    canceled_at: Optional[datetime] = None
    expires_at: Optional[datetime] = None
    description: Optional[str] = None
    metadata_json: Optional[dict[str, Any]] = None
    updated_at: Optional[datetime] = None
    provider_giftcard_id_internal_only: Optional[UUID] = None


class DAOJobEventsCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    job_id: UUID
    event_action: JobEventAction
    message: Optional[str] = None
    host: Optional[str] = None
    retry_count: Optional[int] = None
    extra: Optional[dict[str, Any]] = None
    actor_type: ActorType
    actor_id: Optional[str] = None
    job_type: Optional[str] = None
    photobook_id: Optional[UUID] = None


class DAOJobEventsUpdate(WritableModel):
    job_id: Optional[UUID] = None
    event_action: Optional[JobEventAction] = None
    message: Optional[str] = None
    host: Optional[str] = None
    retry_count: Optional[int] = None
    extra: Optional[dict[str, Any]] = None
    actor_type: Optional[ActorType] = None
    actor_id: Optional[str] = None
    job_type: Optional[str] = None
    photobook_id: Optional[UUID] = None


class DAOJobsCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    job_type: str
    status: JobStatus
    input_payload: Optional[dict[str, Any]] = None
    result_payload: Optional[dict[str, Any]] = None
    error_message: Optional[str] = None
    user_id: Optional[UUID] = None
    photobook_id: Optional[UUID] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    retry_count: Optional[int] = None
    max_retries: Optional[int] = None
    last_attempted_at: Optional[datetime] = None


class DAOJobsUpdate(WritableModel):
    job_type: Optional[str] = None
    status: Optional[JobStatus] = None
    input_payload: Optional[dict[str, Any]] = None
    result_payload: Optional[dict[str, Any]] = None
    error_message: Optional[str] = None
    user_id: Optional[UUID] = None
    photobook_id: Optional[UUID] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    retry_count: Optional[int] = None
    max_retries: Optional[int] = None
    last_attempted_at: Optional[datetime] = None


class DAONotificationDeliveryAttemptsCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    share_channel_id: UUID
    notification_type: Optional[ShareNotificationType] = None
    channel_type: ShareChannelType
    provider: Optional[ShareProvider] = None
    event: NotificationDeliveryEvent
    payload: Optional[dict[str, Any]] = None
    notification_outbox_id: Optional[UUID] = None


class DAONotificationDeliveryAttemptsUpdate(WritableModel):
    share_channel_id: Optional[UUID] = None
    notification_type: Optional[ShareNotificationType] = None
    channel_type: Optional[ShareChannelType] = None
    provider: Optional[ShareProvider] = None
    event: Optional[NotificationDeliveryEvent] = None
    payload: Optional[dict[str, Any]] = None
    notification_outbox_id: Optional[UUID] = None


class DAONotificationOutboxCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    photobook_id: UUID
    share_id: UUID
    share_channel_id: UUID
    channel_type: ShareChannelType
    provider: Optional[ShareProvider] = None
    status: ShareChannelStatus
    scheduled_for: Optional[datetime] = None
    last_error: Optional[str] = None
    last_provider_message_id: Optional[str] = None
    notification_type: ShareNotificationType
    dispatch_token: Optional[UUID] = None
    created_by_user_id: UUID
    dispatch_claimed_at: Optional[datetime] = None
    idempotency_key: Optional[str] = None
    dispatch_lease_expires_at: Optional[datetime] = None
    dispatch_worker_id: Optional[str] = None
    canceled_at: Optional[datetime] = None
    canceled_by_user_id: Optional[UUID] = None
    scheduled_by_user_id: Optional[UUID] = None
    last_scheduled_at: Optional[datetime] = None


class DAONotificationOutboxUpdate(WritableModel):
    photobook_id: Optional[UUID] = None
    share_id: Optional[UUID] = None
    share_channel_id: Optional[UUID] = None
    channel_type: Optional[ShareChannelType] = None
    provider: Optional[ShareProvider] = None
    status: Optional[ShareChannelStatus] = None
    scheduled_for: Optional[datetime] = None
    last_error: Optional[str] = None
    last_provider_message_id: Optional[str] = None
    updated_at: Optional[datetime] = None
    notification_type: Optional[ShareNotificationType] = None
    dispatch_token: Optional[UUID] = None
    created_by_user_id: Optional[UUID] = None
    dispatch_claimed_at: Optional[datetime] = None
    idempotency_key: Optional[str] = None
    dispatch_lease_expires_at: Optional[datetime] = None
    dispatch_worker_id: Optional[str] = None
    canceled_at: Optional[datetime] = None
    canceled_by_user_id: Optional[UUID] = None
    scheduled_by_user_id: Optional[UUID] = None
    last_scheduled_at: Optional[datetime] = None


class DAONotificationsCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    recipient_id: UUID
    actor_id: Optional[UUID] = None
    type: NotificationType
    photobook_id: Optional[UUID] = None
    comment_id: Optional[UUID] = None
    share_id: Optional[UUID] = None
    title: Optional[str] = None
    body: Optional[str] = None
    cta_url: Optional[str] = None
    payload: dict[str, Any]
    group_key: Optional[str] = None
    seen_at: Optional[datetime] = None


class DAONotificationsUpdate(WritableModel):
    recipient_id: Optional[UUID] = None
    actor_id: Optional[UUID] = None
    type: Optional[NotificationType] = None
    photobook_id: Optional[UUID] = None
    comment_id: Optional[UUID] = None
    share_id: Optional[UUID] = None
    title: Optional[str] = None
    body: Optional[str] = None
    cta_url: Optional[str] = None
    payload: Optional[dict[str, Any]] = None
    group_key: Optional[str] = None
    seen_at: Optional[datetime] = None


class DAOPagesCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    photobook_id: Optional[UUID] = None
    page_number: int
    user_message: Optional[str] = None
    layout: Optional[PageLayout] = None
    user_message_alternative_options: Optional[dict[str, Any]] = None
    revision: int
    user_message_alternative_options_outdated: bool
    page_lightweight_title: Optional[str] = None


class DAOPagesUpdate(WritableModel):
    photobook_id: Optional[UUID] = None
    page_number: Optional[int] = None
    user_message: Optional[str] = None
    layout: Optional[PageLayout] = None
    user_message_alternative_options: Optional[dict[str, Any]] = None
    revision: Optional[int] = None
    user_message_alternative_options_outdated: Optional[bool] = None
    page_lightweight_title: Optional[str] = None


class DAOPagesAssetsRelCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    page_id: Optional[UUID] = None
    asset_id: Optional[UUID] = None
    order_index: Optional[int] = None
    caption: Optional[str] = None


class DAOPagesAssetsRelUpdate(WritableModel):
    page_id: Optional[UUID] = None
    asset_id: Optional[UUID] = None
    order_index: Optional[int] = None
    caption: Optional[str] = None


class DAOPaymentEventsCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    payment_id: Optional[UUID] = None
    stripe_event_id: Optional[str] = None
    stripe_event_type: Optional[str] = None
    source: PaymentEventSource
    payload: dict[str, Any]
    signature_verified: Optional[bool] = None
    applied_status: Optional[PaymentStatus] = None
    event_type: Optional[str] = None


class DAOPaymentEventsUpdate(WritableModel):
    payment_id: Optional[UUID] = None
    stripe_event_id: Optional[str] = None
    stripe_event_type: Optional[str] = None
    source: Optional[PaymentEventSource] = None
    payload: Optional[dict[str, Any]] = None
    signature_verified: Optional[bool] = None
    applied_status: Optional[PaymentStatus] = None
    event_type: Optional[str] = None


class DAOPaymentsCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    created_by_user_id: UUID
    photobook_id: UUID
    purpose: PaymentPurpose
    amount_total: int
    currency: str
    stripe_payment_intent_id: Optional[str] = None
    stripe_customer_id: Optional[str] = None
    stripe_payment_method_id: Optional[str] = None
    stripe_latest_charge_id: Optional[str] = None
    status: PaymentStatus
    description: Optional[str] = None
    receipt_email: Optional[str] = None
    idempotency_key: Optional[str] = None
    failure_code: Optional[str] = None
    failure_message: Optional[str] = None
    refunded_amount: int
    metadata_json: dict[str, Any]
    share_create_request: Optional[dict[str, Any]] = None
    fulfilled_at: Optional[datetime] = None
    fulfillment_last_error: Optional[str] = None


class DAOPaymentsUpdate(WritableModel):
    created_by_user_id: Optional[UUID] = None
    photobook_id: Optional[UUID] = None
    purpose: Optional[PaymentPurpose] = None
    amount_total: Optional[int] = None
    currency: Optional[str] = None
    stripe_payment_intent_id: Optional[str] = None
    stripe_customer_id: Optional[str] = None
    stripe_payment_method_id: Optional[str] = None
    stripe_latest_charge_id: Optional[str] = None
    status: Optional[PaymentStatus] = None
    description: Optional[str] = None
    receipt_email: Optional[str] = None
    idempotency_key: Optional[str] = None
    failure_code: Optional[str] = None
    failure_message: Optional[str] = None
    refunded_amount: Optional[int] = None
    metadata_json: Optional[dict[str, Any]] = None
    updated_at: Optional[datetime] = None
    share_create_request: Optional[dict[str, Any]] = None
    fulfilled_at: Optional[datetime] = None
    fulfillment_last_error: Optional[str] = None


class DAOPhotobookBookmarksCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    user_id: UUID
    photobook_id: UUID
    source: Optional[str] = None


class DAOPhotobookBookmarksUpdate(WritableModel):
    user_id: Optional[UUID] = None
    photobook_id: Optional[UUID] = None
    source: Optional[str] = None


class DAOPhotobookCommentsCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    photobook_id: UUID
    user_id: Optional[UUID] = None
    guest_name: Optional[str] = None
    guest_email: Optional[str] = None
    body: str
    status: CommentStatus
    notification_status: NotificationStatus
    commenter_ip: Optional[str] = None
    user_agent: Optional[str] = None
    last_updated_by: Optional[UUID] = None


class DAOPhotobookCommentsUpdate(WritableModel):
    photobook_id: Optional[UUID] = None
    user_id: Optional[UUID] = None
    guest_name: Optional[str] = None
    guest_email: Optional[str] = None
    body: Optional[str] = None
    status: Optional[CommentStatus] = None
    notification_status: Optional[NotificationStatus] = None
    commenter_ip: Optional[str] = None
    user_agent: Optional[str] = None
    updated_at: Optional[datetime] = None
    last_updated_by: Optional[UUID] = None


class DAOPhotobookSettingsCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    photobook_id: UUID
    main_style: Optional[str] = None
    font: FontStyle
    is_comment_enabled: bool
    is_allow_download_all_images_enabled: bool
    is_tipping_enabled: bool


class DAOPhotobookSettingsUpdate(WritableModel):
    photobook_id: Optional[UUID] = None
    main_style: Optional[str] = None
    font: Optional[FontStyle] = None
    is_comment_enabled: Optional[bool] = None
    is_allow_download_all_images_enabled: Optional[bool] = None
    is_tipping_enabled: Optional[bool] = None
    updated_at: Optional[datetime] = None


class DAOPhotobookShareCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    photobook_id: UUID
    email: Optional[str] = None
    invited_user_id: Optional[UUID] = None
    role: ShareRole
    email_notification_status: Optional[NotificationStatus] = None
    custom_message: Optional[str] = None


class DAOPhotobookShareUpdate(WritableModel):
    photobook_id: Optional[UUID] = None
    email: Optional[str] = None
    invited_user_id: Optional[UUID] = None
    role: Optional[ShareRole] = None
    email_notification_status: Optional[NotificationStatus] = None
    custom_message: Optional[str] = None
    updated_at: Optional[datetime] = None


class DAOPhotobooksCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    title: str
    caption: Optional[str] = None
    theme: Optional[str] = None
    status: Optional[PhotobookStatus] = None
    user_provided_occasion: Optional[UserProvidedOccasion] = None
    user_provided_occasion_custom_details: Optional[str] = None
    user_provided_context: Optional[str] = None
    thumbnail_asset_id: Optional[UUID] = None
    deleted_at: Optional[datetime] = None
    status_last_edited_by: Optional[PhotobookStatusEditor] = None
    background_color_palette: Optional[str] = None
    user_gift_recipient: Optional[str] = None
    suggested_overall_gift_message: Optional[str] = None
    suggested_overall_gift_message_tone: Optional[str] = None
    suggested_overall_gift_message_alternative_options: Optional[dict[str, Any]] = None
    user_id: UUID
    background: BackgroundType
    bg_img_name: Optional[str] = None
    open_style: Optional[OpenStyle] = None
    open_param: Optional[dict[str, Any]] = None
    open_confetti: Optional[OpenConfetti] = None


class DAOPhotobooksUpdate(WritableModel):
    title: Optional[str] = None
    caption: Optional[str] = None
    theme: Optional[str] = None
    status: Optional[PhotobookStatus] = None
    updated_at: Optional[datetime] = None
    user_provided_occasion: Optional[UserProvidedOccasion] = None
    user_provided_occasion_custom_details: Optional[str] = None
    user_provided_context: Optional[str] = None
    thumbnail_asset_id: Optional[UUID] = None
    deleted_at: Optional[datetime] = None
    status_last_edited_by: Optional[PhotobookStatusEditor] = None
    background_color_palette: Optional[str] = None
    user_gift_recipient: Optional[str] = None
    suggested_overall_gift_message: Optional[str] = None
    suggested_overall_gift_message_tone: Optional[str] = None
    suggested_overall_gift_message_alternative_options: Optional[dict[str, Any]] = None
    user_id: Optional[UUID] = None
    background: Optional[BackgroundType] = None
    bg_img_name: Optional[str] = None
    open_style: Optional[OpenStyle] = None
    open_param: Optional[dict[str, Any]] = None
    open_confetti: Optional[OpenConfetti] = None


class DAOPhotobooksAssetsRelCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    photobook_id: UUID
    asset_id: UUID


class DAOPhotobooksAssetsRelUpdate(WritableModel):
    photobook_id: Optional[UUID] = None
    asset_id: Optional[UUID] = None


class DAOShareChannelsCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    photobook_share_id: UUID
    photobook_id: UUID
    channel_type: ShareChannelType
    destination: str


class DAOShareChannelsUpdate(WritableModel):
    photobook_share_id: Optional[UUID] = None
    photobook_id: Optional[UUID] = None
    channel_type: Optional[ShareChannelType] = None
    destination: Optional[str] = None
    updated_at: Optional[datetime] = None


class DAOSharesCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    photobook_id: UUID
    created_by_user_id: Optional[UUID] = None
    kind: ShareKind
    sender_display_name: Optional[str] = None
    recipient_display_name: Optional[str] = None
    recipient_user_id: Optional[UUID] = None
    share_slug: str
    access_policy: ShareAccessPolicy
    notes: Optional[str] = None
    revoked_at: Optional[datetime] = None
    revoked_by_user_id: Optional[UUID] = None
    revoked_reason: Optional[str] = None
    created_by_payment_id: Optional[UUID] = None


class DAOSharesUpdate(WritableModel):
    photobook_id: Optional[UUID] = None
    created_by_user_id: Optional[UUID] = None
    kind: Optional[ShareKind] = None
    sender_display_name: Optional[str] = None
    recipient_display_name: Optional[str] = None
    recipient_user_id: Optional[UUID] = None
    share_slug: Optional[str] = None
    access_policy: Optional[ShareAccessPolicy] = None
    notes: Optional[str] = None
    updated_at: Optional[datetime] = None
    revoked_at: Optional[datetime] = None
    revoked_by_user_id: Optional[UUID] = None
    revoked_reason: Optional[str] = None
    created_by_payment_id: Optional[UUID] = None


class DAOSubscriptionsCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    user_id: UUID
    store: str
    product_id: str
    status: SubscriptionStatus
    started_at: datetime
    expires_at: Optional[datetime] = None
    original_transaction_id: Optional[str] = None


class DAOSubscriptionsUpdate(WritableModel):
    user_id: Optional[UUID] = None
    store: Optional[str] = None
    product_id: Optional[str] = None
    status: Optional[SubscriptionStatus] = None
    started_at: Optional[datetime] = None
    expires_at: Optional[datetime] = None
    original_transaction_id: Optional[str] = None
    updated_at: Optional[datetime] = None


class DAOUserRecentlyViewedPhotobookCreate(WritableModel):
    user_id: UUID
    photobook_id: UUID
    viewed_at: datetime


class DAOUserRecentlyViewedPhotobookUpdate(WritableModel):
    user_id: Optional[UUID] = None
    photobook_id: Optional[UUID] = None
    viewed_at: Optional[datetime] = None


class DAOUsersCreate(WritableModel):
    id: Optional[UUID] = Field(default_factory=uuid4)
    email: Optional[str] = None
    phone: Optional[str] = None
    email_confirmed_at: Optional[datetime] = None
    phone_confirmed_at: Optional[datetime] = None
    name: Optional[str] = None
    role: str
    bmc_link: Optional[str] = None


class DAOUsersUpdate(WritableModel):
    email: Optional[str] = None
    phone: Optional[str] = None
    email_confirmed_at: Optional[datetime] = None
    phone_confirmed_at: Optional[datetime] = None
    name: Optional[str] = None
    role: Optional[str] = None
    bmc_link: Optional[str] = None
